### ISSUE TITLE
Can't run app locally

### ISSUE THREAD

**Issue by engineerStuardo** [nhuxhr/musicont#3]
hi, I really like your project and I want to run it locally and I cant. can you help me please? I'm @itastu on expo

![image](https://user-images.githubusercontent.com/72483443/125363364-b7b41d00-e32d-11eb-8c03-28cf2a664450.png)

**Comment by jsxclan** [comment]
Hi Italo 👋

Kindly navigate to your project folder, and update the owner property value that's in ```[PATH]/app.json``` from ```jsxclan``` to your expo username ```itastu```
```
{
	"expo": {
		...
		"owner": "jsxclan",
		...
	}
}
```
If your expo username is ```itastu```, then the owner property value should look like:

```
{
	"expo": {
		...
		"owner": "itastu",
		...
	}
}
```

Let me know if you have any other questions or issues.

Thank you :)

**Comment by engineerStuardo** [comment]
Now it doesnt give me the owner warning instead give this warning "Possible Unhandled Promise Rejection" and I dont know what else to do. Please can you help me?

![image](https://user-images.githubusercontent.com/72483443/125468112-21847bab-6088-4de4-b6bd-fa6572b7a0e5.png)
![image](https://user-images.githubusercontent.com/72483443/125466157-a3b687a0-e317-4ca0-8ff2-a3bc4df91ee7.png)
![image](https://user-images.githubusercontent.com/72483443/125467450-b4bb9926-87a5-44fd-b9f0-a8f8f3754c6e.png)
![image](https://user-images.githubusercontent.com/72483443/125467489-878d8c03-f4bd-417e-9c0b-ec7386724d85.png)

**Comment by jsxclan** [comment]
<h3>Step 1:</h3>

First try to disable Admob and see if the warning still come up.
Navigate to project folder ```[PATH]/src/screens/Loading.js``` and comment line 8 and 39:
```javascript
import { Ads } from '../components'; // on line 8
await Ads.interstitialAds(); // on line 39
```
Now try to run the app again, and see if the warning come up, if the warning come up then follow [Step 2](#step-2)

<h3 id='#step-2'>Step 2:</h3>

Kindly let me know which Expo SDK version you're currently using.
Open your Command Prompt, Bash, or Window Terminal, and run ```expo --version``` to check your Expo SDK version.

If your Expo SDK version is lesser than ```4.5.2```, try to upgrade your Expo CLI using ```npm i -g expo-cli```, and run the application again.

Hope this help.

**Comment by engineerStuardo** [comment]
Yeeeeeees. First Step worked for me. Thanks a lot :) 

Have a great day my friend ;)
